/* definitions generated by preprocessor, copy into defines.h */		
#ifndef	PPINC	
#define	_ATMEGA1284P	// device select: _ATMEGAxxxx
#define	_B1024	// boot size select: _Bxxxx (words), powers of two only
#include	<avr/io.h>	
		
		
/* baud rate register value calculation */		
//#define	CPU_FREQ	7372800
#define F_CPU 7372800UL
#define	BAUD_RATE	115200
#define	BRREG_VALUE	3
		
/* definitions for UART control */		
#define	BAUD_RATE_LOW_REG	UBRR0L
#define	UART_CONTROL_REG	UCSR0B
#define	ENABLE_TRANSMITTER_BIT	TXEN0
#define	ENABLE_RECEIVER_BIT	RXEN0
#define	UART_STATUS_REG	UCSR0A
#define	TRANSMIT_COMPLETE_BIT	TXC0
#define	RECEIVE_COMPLETE_BIT	RXC0
#define	UART_DATA_REG	UDR0
		
/* definitions for SPM control */		
#define	SPMCR_REG	SPMCSR

/* definitions for bootloader and sections*/
#define	PAGESIZE	256
#define	APP_END     0x1F800	
#define BOOT_END    0x1FFFE
#define BOOT_START 0x1F8FF 
#define	LARGE_MEMORY	
		
/* indicate that preprocessor result is included */		
#define	PPINC	
#endif		
