/* definitions generated by preprocessor, copy into defines.h */		
#ifndef	PPINC	
#define	_ATMEGA1284P	// device select: _ATMEGAxxxx
#define	_B1024	// boot size select: _Bxxxx (words), powers of two only
#include	<avr/io.h>	
		
/* define pin for enter-self-prog-mode */		
#define	PROGPORT	PORTD
#define	PROGPIN	PIND
#define	PROG_NO	PD4
		
/* baud rate register value calculation */		
//#define	CPU_FREQ	7372800
#define F_CPU 7372800UL
#define	BAUD_RATE	115200
#define	BRREG_VALUE	3
		
/* definitions for UART control */		
#define	BAUD_RATE_LOW_REG	UBRR0L
#define	UART_CONTROL_REG	UCSR0B
#define	ENABLE_TRANSMITTER_BIT	TXEN0
#define	ENABLE_RECEIVER_BIT	RXEN0
#define	UART_STATUS_REG	UCSR0A
#define	TRANSMIT_COMPLETE_BIT	TXC0
#define	RECEIVE_COMPLETE_BIT	RXC0
#define	UART_DATA_REG	UDR0
		
/* definitions for SPM control */		
#define	SPMCR_REG	SPMCSR
#define	APP_END_STR     "0x1F800\0"	
#define BOOT_END_STR    "0x1FFFE\0"
#define	LARGE_MEMORY	
		
/* definitions for device recognition */		
#define	PARTCODE	0
#define	SIGNATURE_BYTE_1	0x1E
#define	SIGNATURE_BYTE_2	0x97
#define	SIGNATURE_BYTE_3	0x05
		
/* indicate that preprocessor result is included */		
#define	PPINC	
#endif		
